### ISSUE TITLE
Perform Hyperparameter Tuning on Linear Regression

### ISSUE THREAD

**Issue by jash0803** [jash0803/Property_Acquisition_Cost_Predictor#1]
**Objective:** 
- Optimize the Linear Regression model by performing hyperparameter tuning, despite it having fewer hyperparameters compared to other algorithms.

**Tasks:**
  - **Regularization Techniques:**
    - Incorporate Ridge (L2) and Lasso (L1) regularization into the linear regression model to prevent overfitting.
  - **Hyperparameter Identification:**
    - Identify hyperparameters such as the regularization strength parameter \( \alpha \) in Ridge and Lasso regression.
  - **Implement Grid Search:**
    - Set up a grid of \( \alpha \) values to explore.
    - Use cross-validation to evaluate model performance for each \( \alpha \).
  - **Analysis:**
    - Plot validation curves to visualize how changes in \( \alpha \) affect model performance.
    - Select the optimal hyperparameter values based on cross-validation scores.
  - **Documentation:**
    - Explain the impact of regularization on model coefficients and performance.
    - Provide insights into the bias-variance trade-off observed during tuning.

**Explanation:**
- Hyperparameter tuning, even in models with few hyperparameters like linear regression, can significantly influence model performance. Regularization parameters control the complexity of the model and help in generalizing better to unseen data. This issue encourages exploring the delicate balance between underfitting and overfitting, enhancing the model's predictive capabilities.

**Comment by IngaleChinmay04** [comment]
I can give it a try! Can you assign it to me?

**Comment by jash0803** [comment]
@IngaleChinmay04 you are assigned with the issue.

**Comment by jash0803** [comment]
@IngaleChinmay04 your pr has been merged. Thanks for participating in hacktoberfest.

**Comment by IngaleChinmay04** [comment]
Thanks!

**Comment by jash0803** [comment]
@IngaleChinmay04 This repository was part of the open-source event SLOP organised by GDG On Campus DAIICT. So if you want to be part of the event check out https://events.mlh.io/events/11771-slop-4-0. We can consider your pull request for the leaderboard then.

**Comment by IngaleChinmay04** [comment]
Yes I'm interested

**Comment by jash0803** [comment]
give @IngaleChinmay04 100 points

**Comment by jash0803** [comment]
@IngaleChinmay04 check out the leaderboard here: https://slop.dscdaiict.in/leaderboard

**Comment by IngaleChinmay04** [comment]
Where can I find more repos for contribute in this?

**Comment by jash0803** [comment]
@IngaleChinmay04 you could improve the documentation of this repository. I could open up the issue.
